export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_SHIPMENT = 'PENDING_SHIPMENT',
  SHIPPED = 'SHIPPED',
  PENDING_RECEIPT = 'PENDING_RECEIPT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
} 